version: '3'

services:

  redis:
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    image: redis:5.0.3-alpine
    ports:
      - '6379:6379'


  db:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/ver/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/ver/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    restart: always
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - app

volumes:
  pg_data: